name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Arquivo de teste ex: pix_load_testing/pix_payment_invoice.js | favor realizar um doublecheck'
        required: true
        type: string

jobs:
  test-file-check:
    name: "testando se o arquivo ${{ inputs.test_name }} existe dentro de testes-k6/src/"
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: File check
        id: testfile
        run: |
          FILE="${{ inputs.test_name }}"
          if [ -f "$FILE" ]; then
              echo "$FILE exists."
              exit 0
          else
              echo "$FILE dont exists."
              exit 1
          fi
     
      - name: Cancel build on failure
        if: failure()
        run: |-
           curl \
             -X POST \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer ${{ secrets.SEFLTOKEN }}" \
             "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}/cancel" && sleep 15

        
          
  trigger:
    needs: [ test-file-check ]
    runs-on: ubuntu-latest
    if: always() && needs.test-file-check.result == 'success'
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="diggioorg02" 
          repo_name="worflowremote"  
          event_type="trigger-workflow" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
