name: K6 Test Workflow development (NOT USE)
on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'SUB-PATH do test <dir/test.js>'
        type: string
      Branch:
        type: boolean
        description: Branch é a MAIN?
      Path:
        type: boolean
        description: O arquivo existe no PATH testes-k6/src/ na MAIN?
      environment:
        description: 'Test Environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
        - "homolog"
        - "sandbox"
      vus:
        description: 'Virtual Users'
        required: true
        default: '10'
        type: choice
        options:
        - "10"
        - "40"
        - "80"
        - "100"
        - "150"
        - "160"
        - "200"
        - "300"
      duration:
        description: 'Duration in seconds'
        required: true
        type: string

jobs:
  test-file-check:

    name: "Validações do Formulario"
    
    runs-on: ubuntu-latest
    permissions:
      actions: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Verificando se o arquivo ${{ inputs.test_name }} existe dentro de testes-k6/src/"
        run: |
          FILE="./testes-k6/src/${{ inputs.test_name }}"
          if [ -f "$FILE" ]; then
              echo "$FILE exists."
              exit 0
          else
              echo ""${{ inputs.test_name }} NÂO existe dentro do diretorio testes-k6/src/ na branch MAIN""
              exit 1
          fi
          
      - name: "Verificando se o formulario de excução foi preenchido corretamente"
        if: failure() || (inputs.Branch == false || inputs.Path == false) || github.ref != 'refs/heads/main'
        run: |-
           echo "Voce precias executar o teste pela main, sua Branch ${{ github.ref_name }}"
           echo "Crie um PR para a main e execute o teste pela main"
           echo "Valide as informações antes de preencher Formulario"
           echo 'olhe a documentação https://github.com/dlpco/quality-assurance-backend/blob/main/testes-k6/README.md'
           curl -s \
             -X POST \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}/cancel"
           exit 1

        
          
  trigger:
    name: "Run K6 test"
    needs: [ test-file-check ]
    runs-on: ubuntu-latest
    if: always() && needs.test-file-check.result == 'success'
    steps:
      - name: "Run K6 test on ${{ inputs.test_name }}"
        run: |
          # Set the required variables
          repo_owner="diggioorg02" 
          repo_name="worflowremote"  
          event_type="trigger-workflow" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
          exit 1
